name: Publish Latest Docker Image
concurrency: production

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log in to docker hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            jrad/tic-tac-toe

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: deployment/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}