name: Publish Docker Image
concurrency: production

on:
  push:
    branches: [main]
  release:
    types: [published]

  workflow_dispatch: {}

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Github Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            jradin37/mass-tic-tac-toe
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}},priority=1200
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}